version: '3.8'

services:
  rhyme-search-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=8000
    volumes:
      - .:/app
    restart: unless-stopped
